export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILED = 'FETCH_FAILED'
export const EDIT_BOOK = 'EDIT_BOOK'
export const DELETE_BOOK = 'DELETE_BOOK'
export const ADD_BOOK = 'ADD_BOOK'
